
2024-12-09 21:49:23,113 | INFO | "test_challenge" выполнен успешно

2024-12-09 21:49:23,114 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Stepa\PycharmProjects\Module_12\tests_12_4.py", line 31, in test_run
    default_2 = Runner(3.14, 10)
                ^^^^^^^^^^^^^^^^
  File "C:\Users\Stepa\PycharmProjects\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано float

2024-12-09 21:49:23,116 | WARNING | Неверная скорость для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Stepa\PycharmProjects\Module_12\tests_12_4.py", line 16, in test_walk
    walker = Runner('Default', -7)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Stepa\PycharmProjects\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -7
